#!/usr/bin/with-contenv bash

cd /config

if [ ! -f /etc/php7/conf.d/50-koel.ini ]; then
    cp /defaults/php7/50-koel.ini /etc/php7/conf.d/
fi

if [ ! -f /etc/php7/php-fpm.d/koel.conf ]; then
    cp /defaults/php-fpm/koel.conf /etc/php7/php-fpm.d/
fi

if [ -f /etc/nginx/conf.d/default.conf ]; then
    rm /etc/nginx/conf.d/default.conf
    cp /defaults/nginx.conf /etc/nginx/conf.d/koel.conf
fi

rsync -azvP --checksum --ignore-existing \
    /app/ /config

if [ ! -f /config/.env ]; then
    cp .env.example .env
    sed -i 's|DB_CONNECTION=|DB_CONNECTION='$DB_CONNECTION'|g' ./.env
    sed -i 's|DB_HOST=|DB_HOST='$DB_HOST'|g' ./.env
    sed -i 's|DB_DATABASE=|DB_DATABASE='$DB_DATABASE'|g' ./.env
    sed -i 's|DB_USERNAME=|DB_USERNAME='$DB_USERNAME'|g' ./.env
    sed -i 's|DB_PASSWORD=|DB_PASSWORD='$DB_PASSWORD'|g' ./.env
    sed -i 's|ADMIN_EMAIL=|ADMIN_EMAIL='$ADMIN_EMAIL'|g' ./.env
    sed -i 's|ADMIN_NAME=|ADMIN_NAME='$ADMIN_NAME'|g' ./.env
    sed -i 's|ADMIN_PASSWORD=|ADMIN_PASSWORD='$ADMIN_PASSWORD'|g' ./.env
    sed -i 's|/usr/local/bin/ffmpeg|/usr/bin/ffmpeg|g' ./.env
    sed -i 's|STREAMING_METHOD=php|STREAMING_METHOD=x-accel-redirect|g' ./.env
fi

if [ ! -d /config/vendor ]; then
    composer install
    php artisan koel:init
fi

# permissions
chown -R abc:abc \
	/config

chmod -R 777 \
    /config/storage
